server:
  compression:
    enabled: true
    min-response-size: 2048
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  servlet:
    multipart:
      max-file-size: 10240000
      max-request-size: 10240000
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
# turn eureka off by default
eureka:
  client:
    enabled: false
#logging:
#  path: D:\fnb-ws
#  level:
#    org.springframework.jdbc.core: trace
#    org.springframework.jdbc.core.BeanPropertyRowMapper: info
#    org.hibernate.type: trace
---
spring:
  profiles: eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/epb
    username: epb
    password: 9209
---
spring:
  profiles: oracle
  datasource:
    url: jdbc:oracle:thin:LSTUDIO/EPB@//192.168.0.17:1521/orcl
    username: LSTUDIO
    password: EPB
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect